//! Streaming plumbing smoke test — Phase 1 §8 step 9.
//!
//! Spins up the scheduler (no real Postgres) with a synthetic broadcast sender,
//! feeds 1000 synthetic `InvalidationEvent`s for 50 distinct `(chain, mint)`
//! pairs, and asserts:
//!
//! - Workers drain without deadlock (completes within 10s wall-clock).
//! - `streaming_debounce_merge_total` ≥ 800 (burst collapsing).
//! - `streaming_queue_depth` gauge returns to 0.
//! - No panic, no task death.
//!
//! No Postgres in this test — Phase 1 workers return `Ok(())` without DB writes.

use std::sync::Arc;
use std::time::{Duration, Instant};

use chrono::DateTime;
use tokio::sync::{RwLock, broadcast};

use mg_onchain_common::chain::Chain;
use mg_onchain_gateway::state::InvalidationEvent;
use mg_onchain_server::streaming::registry::StreamingRegistry;
use mg_onchain_server::streaming::scheduler::DetectorScheduler;
use mg_onchain_server::streaming::worker::SchedulerWorker;
use mg_onchain_server::streaming_config::StreamingConfig;
use mg_onchain_server::streaming_metrics::StreamingMetrics;

/// Build a config tuned for the smoke test:
/// - debounce_window_ms = 50 (short, so we don't have to wait 500ms)
/// - queue_capacity = 256
/// - per_detector_timeout_ms = 100 (irrelevant in Phase 1 — no detectors)
fn smoke_config() -> StreamingConfig {
    StreamingConfig {
        enabled: true,
        debounce_window_ms: 50,
        queue_capacity: 256,
        worker_count: 4,
        window_minutes: 60,
        gc_interval_seconds: 120,
        max_streaming_tokens: 5000,
        streaming_idle_timeout_minutes: 60,
        per_detector_timeout_ms: 100,
        scoring_skip_delta_threshold: 0.05,
        streaming_d01_cadence_n: 10,
        token_risk_reports_enabled: false,
    }
}

/// 50 distinct synthetic mint addresses (valid Solana base58 — 32 bytes each).
///
/// Generated by encoding `[i as u8, 0, 0, ..., 0]` (32 bytes) into base58.
/// All addresses are structurally valid Solana public keys.
fn synthetic_mints(n: usize) -> Vec<String> {
    (0..n)
        .map(|i| {
            let mut bytes = [0u8; 32];
            // Use two bytes so we can support n > 255.
            bytes[0] = (i & 0xFF) as u8;
            bytes[1] = ((i >> 8) & 0xFF) as u8;
            bs58::encode(&bytes).into_string()
        })
        .collect()
}

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn streaming_plumbing_smoke_test() {
    // ----------------------------------------------------------------
    // Setup
    // ----------------------------------------------------------------
    let config = smoke_config();
    let metrics = Arc::new(StreamingMetrics::new().expect("metrics init"));

    let (invalidation_tx, _) = broadcast::channel::<InvalidationEvent>(1024);

    let idle_timeout = chrono::Duration::minutes(config.streaming_idle_timeout_minutes as i64);
    let registry = Arc::new(RwLock::new(StreamingRegistry::new(
        config.max_streaming_tokens,
        idle_timeout,
    )));

    let (queue_tx, queue_rx) = async_channel::bounded(config.queue_capacity);

    // ----------------------------------------------------------------
    // Spawn scheduler
    // ----------------------------------------------------------------
    let scheduler = DetectorScheduler {
        invalidation_rx: invalidation_tx.subscribe(),
        queue_tx,
        registry: registry.clone(),
        config: config.clone(),
        metrics: metrics.clone(),
    };
    tokio::spawn(scheduler.run());

    // ----------------------------------------------------------------
    // Spawn workers (4 for smoke test)
    // ----------------------------------------------------------------
    for _ in 0..config.worker_count {
        let worker = SchedulerWorker {
            queue_rx: queue_rx.clone(),
            config: config.clone(),
            metrics: metrics.clone(),
            detectors: vec![],
            // Phase 1 plumbing: no real detectors → optional deps unused.
            store: None,
            registry: None,
            scoring: None,
            detector_config: None,
            risk_report_store: None,
        };
        tokio::spawn(worker.run());
    }

    // ----------------------------------------------------------------
    // Feed 1000 events for 50 distinct (chain, mint) pairs
    // (20 bursts per token — most should be debounce-merged)
    // ----------------------------------------------------------------
    let mints = synthetic_mints(50);
    let base_block_time = 1_700_000_000_i64; // 2023-11-14

    for i in 0u32..1000 {
        let mint = mints[(i as usize) % mints.len()].clone();
        let block_time = base_block_time + i as i64;
        let slot = 300_000_000u64 + i as u64;
        let ev = InvalidationEvent {
            chain: Chain::Solana,
            mint,
            block_time,
            slot_hints: vec![slot],
        };
        // best-effort send; ignore if no active receiver (scheduler may lag)
        let _ = invalidation_tx.send(ev);
    }

    // ----------------------------------------------------------------
    // Wait for workers to drain — poll queue depth with 10s timeout
    // ----------------------------------------------------------------
    let deadline = Instant::now() + Duration::from_secs(10);
    loop {
        // Give the debounce ticker a couple of cycles to fire.
        tokio::time::sleep(Duration::from_millis(200)).await;

        let depth = metrics.streaming_queue_depth.get();
        let queue_len = queue_rx.len();
        if depth == 0.0 && queue_len == 0 {
            break;
        }
        if Instant::now() > deadline {
            panic!("smoke test timed out: queue_depth={depth}, queue_rx.len()={queue_len}");
        }
    }

    // ----------------------------------------------------------------
    // Assert: debounce merge count ≥ 800
    // (1000 events for 50 tokens → ideally each token gets ~1 job = 50 enqueued;
    // ~950 merges; we allow ≥ 800 for scheduling jitter)
    // ----------------------------------------------------------------
    let merge_count = metrics.streaming_debounce_merge_total.get();
    assert!(
        merge_count >= 800.0,
        "expected ≥ 800 debounce merges, got {merge_count}"
    );

    // ----------------------------------------------------------------
    // Assert: queue depth is 0
    // ----------------------------------------------------------------
    let final_depth = metrics.streaming_queue_depth.get();
    assert_eq!(
        final_depth, 0.0,
        "queue depth must return to 0 after drain, got {final_depth}"
    );

    // ----------------------------------------------------------------
    // Assert: at least one evaluation completed (outcome=ok)
    // ----------------------------------------------------------------
    let ok_count = metrics
        .streaming_evaluations_total
        .with_label_values(&["solana", "ok"])
        .get();
    assert!(
        ok_count >= 1.0,
        "at least one evaluation must complete successfully, got {ok_count}"
    );
}

// ---------------------------------------------------------------------------
// Additional determinism smoke test: explicit block_time → observed_at
// ---------------------------------------------------------------------------

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn scheduler_derives_observed_at_from_block_time_not_wall_clock() {
    // Send a single invalidation event with a known block_time.
    // Verify the scheduler builds a job with that exact observed_at.
    let config = StreamingConfig {
        debounce_window_ms: 30,
        ..smoke_config()
    };
    let metrics = Arc::new(StreamingMetrics::new().unwrap());
    let (invalidation_tx, _) = broadcast::channel::<InvalidationEvent>(16);

    let idle_timeout = chrono::Duration::minutes(60);
    let registry = Arc::new(RwLock::new(StreamingRegistry::new(100, idle_timeout)));

    let (queue_tx, queue_rx) = async_channel::bounded(16);

    // Use a known block_time.
    let known_block_time: i64 = 1_700_100_000;
    let expected_observed_at =
        DateTime::<chrono::Utc>::from_timestamp(known_block_time, 0).expect("valid timestamp");

    let scheduler = DetectorScheduler {
        invalidation_rx: invalidation_tx.subscribe(),
        queue_tx,
        registry: registry.clone(),
        config: config.clone(),
        metrics: metrics.clone(),
    };
    tokio::spawn(scheduler.run());

    // Send one event with a valid Solana base58 address (32 zero bytes).
    // bs58::encode([0u8; 32]) = "11111111111111111111111111111111"
    let test_mint = bs58::encode([42u8; 32]).into_string();
    let ev = InvalidationEvent {
        chain: Chain::Solana,
        mint: test_mint.clone(),
        block_time: known_block_time,
        slot_hints: vec![12345],
    };
    invalidation_tx.send(ev).unwrap();

    // Wait for the debounce window to fire and a job to appear.
    let deadline = Instant::now() + Duration::from_secs(5);
    loop {
        tokio::time::sleep(Duration::from_millis(50)).await;
        if !queue_rx.is_empty() {
            break;
        }
        if Instant::now() > deadline {
            panic!("no job appeared within 5 seconds");
        }
    }

    let job = queue_rx.recv().await.expect("job must be present");
    assert_eq!(
        job.observed_at, expected_observed_at,
        "observed_at must equal block_time-derived timestamp, not wall-clock"
    );
    assert_eq!(job.slot_hints, vec![12345u64]);
}
