//! `RawLog` — the raw on-chain log format, as received from `eth_getLogs` or
//! decoded from a block's `receipts`.
//!
//! This is the common input to all `DecodeLog` implementations generated by the
//! `event_signature!` macro.  All topic values are `B256`; the data field is raw
//! bytes.  String addresses are NOT used here — the adapter layer normalises
//! addresses to `Address` before constructing `RawLog`.

use serde::{Deserialize, Serialize};

use crate::{Address, B256};

/// A raw EVM event log, exactly as delivered by `eth_getLogs`.
///
/// Field names mirror the JSON-RPC `eth_getLogs` response schema.
///
/// `topics[0]` is the event signature hash (topic0).  For anonymous events,
/// `topics` may be empty.  Indexed event parameters occupy `topics[1..n]`
/// (max 3 indexed params per EVM spec).
///
/// `data` contains ABI-encoded non-indexed parameters.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RawLog {
    /// The address of the contract that emitted the log.
    pub address: Address,
    /// Topic list: `[topic0, indexed_param_1, ..., indexed_param_n]`.
    pub topics: Vec<B256>,
    /// ABI-encoded non-indexed parameters.
    pub data: Vec<u8>,
}

impl RawLog {
    /// Construct a new `RawLog`.
    pub fn new(address: Address, topics: Vec<B256>, data: Vec<u8>) -> Self {
        Self { address, topics, data }
    }

    /// Return `topics[0]` (the event signature hash) if present.
    #[must_use]
    pub fn topic0(&self) -> Option<&B256> {
        self.topics.first()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::str::FromStr;

    #[test]
    fn raw_log_topic0() {
        let topic0: B256 =
            "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"
                .parse()
                .unwrap();
        let log = RawLog::new(Address::ZERO, vec![topic0], vec![]);
        assert_eq!(log.topic0(), Some(&topic0));
    }

    #[test]
    fn raw_log_no_topics() {
        let log = RawLog::new(Address::ZERO, vec![], vec![]);
        assert!(log.topic0().is_none());
    }

    #[test]
    fn raw_log_serde_round_trip() {
        let log = RawLog {
            address: Address::from_str("0x0000000000000000000000000000000000000001").unwrap(),
            topics: vec![B256::ZERO],
            data: vec![0xab, 0xcd],
        };
        let json = serde_json::to_string(&log).unwrap();
        let back: RawLog = serde_json::from_str(&json).unwrap();
        assert_eq!(log, back);
    }
}
