//! `DecodeLog` trait — implemented by all types generated by `event_signature!`.
//!
//! The macro generates an `impl DecodeLog for <EventName>` that:
//! 1. Checks `log.topic0()` against `Self::SIGNATURE_HASH`.
//! 2. Decodes indexed parameters from `log.topics[1..]` (each is a 32-byte slot).
//! 3. Decodes non-indexed parameters from `log.data` using `abi::decode::*`.

use crate::abi::DecodeError;
use crate::log::RawLog;

/// Trait implemented by typed event structs.
///
/// # Usage
///
/// ```ignore
/// use mg_evm_types::event::DecodeLog;
///
/// // Generated by event_signature! macro:
/// // let transfer = Transfer::decode_log(&raw_log)?;
/// ```
pub trait DecodeLog: Sized {
    /// Decode a `RawLog` into `Self`, returning `Err(DecodeError)` on failure.
    ///
    /// Implementors must:
    /// 1. Verify `log.topic0() == Some(&Self::SIGNATURE_HASH)` →
    ///    `Err(DecodeError::Topic0Mismatch)` otherwise.
    /// 2. Verify `log.topics.len() == expected_topic_count` →
    ///    `Err(DecodeError::WrongTopicCount)` otherwise.
    /// 3. Decode indexed params from `log.topics[1..]`.
    /// 4. Decode non-indexed params from `log.data`.
    fn decode_log(log: &RawLog) -> Result<Self, DecodeError>;
}
