//! Code generator for `event_signature!`.
//!
//! Given a parsed `EventDecl`, emits:
//!
//! 1. A `pub struct <Name> { pub field: RustType, ... }` — one field per parameter.
//! 2. `impl <Name> { pub const SIGNATURE_HASH: mg_evm_types::B256 = …; }` — the
//!    keccak256 of the canonical signature string, computed at macro-expansion time
//!    by this proc-macro using `tiny-keccak` and emitted as a byte-array literal.
//! 3. `impl mg_evm_types::DecodeLog for <Name>` — decodes a `RawLog`.
//!
//! # SIGNATURE_HASH strategy
//!
//! `tiny-keccak` is not `const fn`.  The options were:
//! a) Runtime `OnceLock` — simple but not a `const`.
//! b) Compute the hash **inside the proc-macro** at expansion time, then emit the
//!    32 bytes as a literal `mg_evm_types::B256([0xab, 0xcd, …])`.
//!
//! We chose (b): the hash is computed once at compile time inside the proc-macro
//! process (which is just a normal Rust binary), and the result is baked into the
//! generated code as a constant byte-array literal.  This gives a true `const` with
//! zero runtime overhead.
//!
//! reference: alloy-sol-macro generate.rs (MIT/Apache-2.0) — approach of emitting
//!            the hash as a literal consulted.

use proc_macro2::TokenStream;
use quote::quote;
use tiny_keccak::{Hasher as _, Keccak};

use crate::parse::{EventDecl, EventParam, SolType};

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

/// Generate the complete token stream for one event declaration.
pub fn generate(decl: &EventDecl) -> TokenStream {
    let struct_def = generate_struct(decl);
    let impl_block = generate_impl(decl);
    let decode_impl = generate_decode_log(decl);

    quote! {
        #struct_def
        #impl_block
        #decode_impl
    }
}

// ---------------------------------------------------------------------------
// Struct generation
// ---------------------------------------------------------------------------

fn generate_struct(decl: &EventDecl) -> TokenStream {
    let name = &decl.name;
    let fields: Vec<TokenStream> = decl.params.iter().map(|p| {
        let field_name = &p.name;
        let field_type = rust_type(&p.ty);
        quote! { pub #field_name: #field_type }
    }).collect();

    quote! {
        /// Auto-generated by `mg_evm_types_macros::event_signature!`.
        ///
        /// Field names match the Solidity event parameter names exactly (camelCase is
        /// preserved from the Solidity source).  The `#[allow(non_snake_case)]` attribute
        /// suppresses the lint for Solidity-idiomatic camelCase field names.
        #[allow(non_snake_case)]
        #[derive(Debug, Clone, PartialEq, Eq)]
        pub struct #name {
            #(#fields),*
        }
    }
}

// ---------------------------------------------------------------------------
// `impl <Name>` — SIGNATURE_HASH const
// ---------------------------------------------------------------------------

fn generate_impl(decl: &EventDecl) -> TokenStream {
    let name = &decl.name;
    let canonical_sig = canonical_signature(decl);
    let hash_bytes = keccak256_bytes(canonical_sig.as_bytes());
    let byte_literals: Vec<TokenStream> = hash_bytes.iter().map(|b| quote! { #b }).collect();

    quote! {
        #[allow(non_snake_case)]
        impl #name {
            /// keccak256 of the canonical event signature, computed at compile time.
            /// This is the expected `topics[0]` value in matching `RawLog`s.
            pub const SIGNATURE_HASH: ::mg_evm_types::B256 =
                ::mg_evm_types::B256([#(#byte_literals),*]);
        }
    }
}

// ---------------------------------------------------------------------------
// `impl DecodeLog` — RawLog decoder
// ---------------------------------------------------------------------------

fn generate_decode_log(decl: &EventDecl) -> TokenStream {
    let name = &decl.name;
    let indexed_params: Vec<&EventParam> = decl.params.iter().filter(|p| p.indexed).collect();
    let non_indexed: Vec<&EventParam> = decl.params.iter().filter(|p| !p.indexed).collect();

    // topic count = 1 (signature hash) + number of indexed params
    let expected_topics = 1 + indexed_params.len();

    // Generate decode statements for indexed params (from topics[1..])
    let indexed_decodes: Vec<TokenStream> = indexed_params
        .iter()
        .enumerate()
        .map(|(i, p)| {
            let topic_idx = i + 1; // topics[0] is the signature hash
            let field_name = &p.name;
            let decode_expr = decode_indexed(&p.ty, topic_idx);
            quote! { let #field_name = #decode_expr?; }
        })
        .collect();

    // Generate decode for non-indexed params from `data`
    let non_indexed_decodes = generate_non_indexed_decodes(&non_indexed);

    // Build the struct literal
    let field_inits: Vec<TokenStream> = decl.params.iter().map(|p| {
        let field_name = &p.name;
        quote! { #field_name }
    }).collect();

    quote! {
        #[allow(non_snake_case)]
        impl ::mg_evm_types::DecodeLog for #name {
            fn decode_log(log: &::mg_evm_types::RawLog) -> ::std::result::Result<Self, ::mg_evm_types::DecodeError> {
                #[allow(non_snake_case)]
                // Verify topic0
                let topic0 = log.topic0().ok_or(::mg_evm_types::DecodeError::WrongTopicCount {
                    expected: #expected_topics,
                    got: 0,
                })?;
                if *topic0 != Self::SIGNATURE_HASH {
                    return ::std::result::Result::Err(::mg_evm_types::DecodeError::Topic0Mismatch {
                        expected: ::std::format!("{}", Self::SIGNATURE_HASH),
                        got: ::std::format!("{}", topic0),
                    });
                }
                // Verify topic count
                if log.topics.len() != #expected_topics {
                    return ::std::result::Result::Err(::mg_evm_types::DecodeError::WrongTopicCount {
                        expected: #expected_topics,
                        got: log.topics.len(),
                    });
                }

                // Decode indexed parameters from topics[1..]
                #(#indexed_decodes)*

                // Decode non-indexed parameters from data
                #non_indexed_decodes

                ::std::result::Result::Ok(Self { #(#field_inits),* })
            }
        }
    }
}

/// Generate the decode statements for non-indexed parameters.
///
/// Non-indexed params are ABI-encoded in `log.data` as a flat tuple.
/// Each field occupies one 32-byte "head" slot at position `i * 32`.
/// - Static types: the value is at `i * 32` directly.
/// - Dynamic types: the head slot at `i * 32` is a pointer to the tail; we pass
///   `i * 32` as the `head_offset` argument to `decode_bytes_dynamic` /
///   `decode_string`, which read the pointer themselves.
///
/// Emits a `let _data = &log.data;` binding followed by individual `let field = ...?;`
/// bindings directly in the outer scope (not wrapped in a block) so that the
/// generated field names are in scope for the `Ok(Self { ... })` return.
fn generate_non_indexed_decodes(params: &[&EventParam]) -> TokenStream {
    if params.is_empty() {
        return quote! {};
    }

    // For each param, emit a let binding using the appropriate decode function.
    let field_decodes: Vec<TokenStream> = params.iter().enumerate().map(|(i, p)| {
        let field_name = &p.name;
        let decode_expr = decode_non_indexed_at_offset(&p.ty, i);
        quote! { let #field_name = #decode_expr?; }
    }).collect();

    // Emit into outer scope — no wrapping block.
    quote! {
        let _data: &[u8] = &log.data;
        #(#field_decodes)*
    }
}

/// Emit the decode expression for an indexed param (from a topic slot).
///
/// Indexed params are stored as 32-byte ABI-encoded slots in the topics array.
/// `topic_idx` is the 0-based index into `log.topics`.
fn decode_indexed(ty: &SolType, topic_idx: usize) -> TokenStream {
    let slot_expr = quote! {
        {
            let __topic = &log.topics[#topic_idx];
            __topic.as_bytes().as_slice()
        }
    };

    match ty {
        SolType::Address => quote! {
            ::mg_evm_types::abi::decode_address(#slot_expr, 0)
        },
        SolType::Bool => quote! {
            ::mg_evm_types::abi::decode_bool(#slot_expr, 0)
        },
        SolType::Uint(_bits) => quote! {
            ::mg_evm_types::abi::decode_uint(#slot_expr, 0, 256)
        },
        SolType::Int(_bits) => quote! {
            ::mg_evm_types::abi::decode_int(#slot_expr, 0, 256)
        },
        SolType::BytesFixed(n) => quote! {
            ::mg_evm_types::abi::decode_bytes_fixed(#slot_expr, 0, #n)
        },
        // Dynamic types (bytes, string) are not allowed as indexed in Solidity
        // (they are stored as keccak256 of the value, not ABI-encoded).
        // We emit an error at decode time — these cannot be reconstructed.
        SolType::Bytes | SolType::String => quote! {
            ::std::result::Result::Err(::mg_evm_types::DecodeError::InvalidBitWidth(0))
                as ::std::result::Result<Vec<u8>, _>
        },
    }
}

/// Emit the decode expression for a non-indexed param at field position `field_idx`
/// in `_data`.
///
/// The ABI spec defines a flat tuple encoding in `log.data`:
/// - Field `i` occupies head slot at `i * 32`.
/// - For static types: the value IS the 32-byte slot at `i * 32`.
/// - For dynamic types: the slot at `i * 32` is a pointer; `decode_bytes_dynamic`
///   reads it to find the actual data.
///
/// We compute offsets statically from `field_idx * 32` — no `_offsets` array needed.
fn decode_non_indexed_at_offset(ty: &SolType, field_idx: usize) -> TokenStream {
    let head_offset = field_idx * 32;
    match ty {
        SolType::Address => quote! {
            ::mg_evm_types::abi::decode_address(_data, #head_offset)
        },
        SolType::Bool => quote! {
            ::mg_evm_types::abi::decode_bool(_data, #head_offset)
        },
        SolType::Uint(_bits) => quote! {
            ::mg_evm_types::abi::decode_uint(_data, #head_offset, 256)
        },
        SolType::Int(_bits) => quote! {
            ::mg_evm_types::abi::decode_int(_data, #head_offset, 256)
        },
        SolType::BytesFixed(n) => quote! {
            ::mg_evm_types::abi::decode_bytes_fixed(_data, #head_offset, #n)
        },
        // For dynamic types the head slot at `head_offset` contains the pointer.
        // `decode_bytes_dynamic` reads the pointer from `head_offset` and returns the data.
        SolType::Bytes => quote! {
            ::mg_evm_types::abi::decode_bytes_dynamic(_data, #head_offset, 0)
        },
        SolType::String => quote! {
            ::mg_evm_types::abi::decode_string(_data, #head_offset, 0)
        },
    }
}

// ---------------------------------------------------------------------------
// Rust type mapping
// ---------------------------------------------------------------------------

/// Map a `SolType` to the corresponding Rust type token.
fn rust_type(ty: &SolType) -> TokenStream {
    match ty {
        SolType::Address => quote! { ::mg_evm_types::Address },
        SolType::Bool => quote! { bool },
        SolType::Uint(_) => quote! { ::mg_evm_types::U256 },
        SolType::Int(_) => quote! { ::mg_evm_types::I256 },
        SolType::BytesFixed(_) => quote! { Vec<u8> },
        SolType::Bytes => quote! { Vec<u8> },
        SolType::String => quote! { ::std::string::String },
    }
}

// ---------------------------------------------------------------------------
// Canonical signature helper
// ---------------------------------------------------------------------------

/// Build the canonical ABI event signature string.
///
/// For `Transfer(address indexed from, address indexed to, uint256 value)`:
/// → `"Transfer(address,address,uint256)"`
///
/// The indexed keyword is NOT included in the canonical signature.
/// reference: https://docs.soliditylang.org/en/latest/abi-spec.html
pub fn canonical_signature(decl: &EventDecl) -> String {
    let params: Vec<String> = decl.params.iter().map(|p| p.ty.canonical()).collect();
    format!("{}({})", decl.name, params.join(","))
}

// ---------------------------------------------------------------------------
// Keccak-256 helper (runs at macro expansion time)
// ---------------------------------------------------------------------------

/// Compute keccak256 inside the proc-macro at expansion time.
///
/// Returns raw bytes so we can emit them as a literal array.
/// This runs in the proc-macro host process — no const-fn required.
fn keccak256_bytes(data: &[u8]) -> [u8; 32] {
    let mut k = Keccak::v256();
    k.update(data);
    let mut out = [0u8; 32];
    k.finalize(&mut out);
    out
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parse::EventDecl;
    use syn::parse_str;

    #[test]
    fn canonical_sig_transfer() {
        let decl: EventDecl = parse_str(
            "event Transfer(address indexed from, address indexed to, uint256 value);",
        )
        .unwrap();
        assert_eq!(canonical_signature(&decl), "Transfer(address,address,uint256)");
    }

    #[test]
    fn canonical_sig_univ2_swap() {
        let decl: EventDecl = parse_str(
            "event Swap(address indexed sender, uint256 amount0In, uint256 amount1In, \
             uint256 amount0Out, uint256 amount1Out, address indexed to);",
        )
        .unwrap();
        assert_eq!(
            canonical_signature(&decl),
            "Swap(address,uint256,uint256,uint256,uint256,address)"
        );
    }

    #[test]
    fn keccak_transfer_at_expansion_time() {
        let hash = keccak256_bytes(b"Transfer(address,address,uint256)");
        assert_eq!(
            hex::encode(hash),
            "ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"
        );
    }

    #[test]
    fn keccak_univ2_swap_at_expansion_time() {
        let hash = keccak256_bytes(b"Swap(address,uint256,uint256,uint256,uint256,address)");
        assert_eq!(
            hex::encode(hash),
            "d78ad95fa46c994b6551d0da85fc275fe613ce37657fb8d5e3d130840159d822"
        );
    }
}
